project:
  name: ps-ws-test-1
  s3_regional_buckets: true
  shorten_stack_name: true
  package_lambda: false
  regions:
  - ap-southeast-1
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/main.template.yaml
    regions:
    - us-west-1
    parameters:
      AvailabilityZones: "$[taskcat_genaz_2]"
      EmailAddress: email@yourdomain.com
      KeyPairName: YOUR-KEYPAIR-HERE
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "ps-ws-test-1/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

